--- 
abstract: routines (cos,sin,primes,hailstone,euler,fibbonaci etc) with big numbers
author: Tels <nospam-abuse@bloodgate.com>
build_requires: 
  Test::More: 0.42
distribution_type: module
generated_by: Module::Install version 0.65
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Math-Big
no_index: 
  directory: 
    - examples
    - inc
    - t
requires: 
  Math::BigFloat: 1.55
  Math::BigInt: 1.83
  perl: 5.6.2
version: 1.12
