--- #YAML:1.0
name: Math-Big
version: 1.11
version_from: lib/Math/Big.pm
license: perl
distribution_type: module
generated_by: Math-Big version 1.11
installdirs: site
requires:
  Math::BigFloat: 1.48
  Math::BigInt: 1.74
